version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/github_action_test
    overwrite: yes
permissions:
  - object: /home/ubuntu/github_action_test
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  BeforeInstall:
    - location: deploy-before.sh
      runas: root
  ApplicationStart:
    - location: deploy-after.sh
      timeout: 60
      runas: root